#!/bin/bash
#
# install-suricata-ips.sh
# ---------------------------------------------------------------------------
# Inline Suricata IPS installer for Linux (Wazuh sensor).
#
# What it does:
#   1. Installs Suricata with NFQUEUE (inline) support.
#   2. Builds an iptables FORWARD/INPUT chain that pushes traffic into
#      NFQUEUE where Suricata verdicts (accept/drop).
#   3. Installs a systemd unit (with watchdog), EVE JSON output, and the
#      Wazuh localfile that forwards eve.json to the manager.
#   4. Downloads the ET Open ruleset via suricata-update and VALIDATES the
#      full config BEFORE going inline. Bad config => no NFQUEUE hook =>
#      traffic keeps flowing.
#
# Interface selection (priority):
#   1. $SURICATA_IFACE env var (non-interactive fleet deploys)
#   2. Interactive picker (TTY only, 10s timeout)
#   3. Auto-detect via default route
#
# Mode hardening:
#   - fail-open: engine dies => kernel ACCEPTs queued packets (no network cut).
#     Set SURICATA_FAIL_CLOSED=1 to restore the old fail-closed behaviour.
#   - iptables hook is installed ONLY after `suricata -T` validation passes.
#   - The hook is added AFTER Suricata is running, never before.
#
# Idempotent: re-running is safe. `uninstall-suricata-ips.sh` reverts it.
# ---------------------------------------------------------------------------

set -euo pipefail

NAME="suricata-ips"
QUEUE_NUM="${SURICATA_QUEUE:-0}"
WAZUH_OSSEC="/var/ossec"
EVE_LOG="/var/log/suricata/eve.json"
CONFIG_DIR="/etc/suricata"
ROLES_CONF="/etc/${NAME}.conf"
# Trusted sources bypass NFQUEUE entirely (zero self-block + lower engine load).
# Override: SURICATA_TRUSTED_IPS="ip1 ip2" — empty string disables.
TRUSTED_IPS="${SURICATA_TRUSTED_IPS:-10.3.11.40 172.16.10.49 172.16.10.50 172.16.10.51 172.16.10.52 172.16.10.53}"

fail() { echo "[ERROR] $*" >&2; exit 1; }

[ "$EUID" -eq 0 ] || fail "Run as root (sudo)."

# ---------------------------------------------------------------
# 0. Interface selection: env -> interactive (TTY) -> auto-detect
# ---------------------------------------------------------------
AUTO_IFACE="$(ip -4 route show default 2>/dev/null | awk '{print $5; exit}')"
AUTO_IFACE="${AUTO_IFACE:-$(ip -o route get 1.1.1.1 2>/dev/null | awk '{print $5; exit}')}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

if [ -n "${SURICATA_IFACE:-}" ]; then
    IFACE="$SURICATA_IFACE"
elif [ -t 0 ] && [ -t 1 ]; then
    echo "Available interfaces on $(hostname):"
    ip -br link | awk '$1 != "lo" {printf "  [%d] %s  %s\n", ++n, $1, $2}'
    read -r -t 10 -p "Select interface [${AUTO_IFACE:-none}] (10s): " USER_IFACE || true
    IFACE="${USER_IFACE:-$AUTO_IFACE}"
else
    IFACE="$AUTO_IFACE"
fi

[ -n "$IFACE" ] || fail "No interface detected/selected. Set SURICATA_IFACE=<iface> or run from a TTY."
ip link show "$IFACE" >/dev/null 2>&1 || fail "Interface '$IFACE' does not exist on this host."

if [ "${SURICATA_FAIL_CLOSED:-0}" = "1" ]; then
    FAIL_MODE="fail-closed"
    FAIL_OPEN_YAML="no"
    IPT_TAIL="DROP"
else
    FAIL_MODE="fail-open (engine dies => traffic flows)"
    FAIL_OPEN_YAML="yes"
    IPT_TAIL="ACCEPT"
fi

echo "=============================================="
echo "   Suricata Inline IPS Installer"
echo "=============================================="
echo "[*] Interface : ${IFACE}"
echo "[*] NFQUEUE   : ${QUEUE_NUM}"
echo "[*] Fail mode : ${FAIL_MODE}"
echo ""

# ---------------------------------------------------------------
# 1. Install packages
# ---------------------------------------------------------------
echo "[+] Installing dependencies..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y --no-install-recommends \
    suricata \
    iptables \
    iproute2 \
    jq \
    python3 \
    ca-certificates
# Note: suricata 8.x ships suricata-update inside the main package,
# so it is NOT listed here (would cause a dpkg file-conflict on .deb overlap).

# Make sure the kernel module for NFQUEUE verdicts is present
modprobe nfnetlink_queue 2>/dev/null || true

# Stop any conflicting suricata.service (Ubuntu ships one from the OISF pkg)
# so NFQUEUE queue 0 is free for our unit.
if systemctl list-unit-files suricata.service >/dev/null 2>&1; then
    systemctl stop suricata.service 2>/dev/null || true
    systemctl disable suricata.service 2>/dev/null || true
    # disable alone is not enough: postinst/timers can still start it.
    # mask = symlink to /dev/null, kernel-level "never start again".
    systemctl mask suricata.service 2>/dev/null || true
fi

# ---------------------------------------------------------------
# 2. Write tunables / role config
# ---------------------------------------------------------------
echo "[+] Writing ${ROLES_CONF}"
cat > "${ROLES_CONF}" <<EOF
# Generated by install-suricata-ips.sh -- edit to persist across reinstalls
SURICATA_IFACE=${IFACE}
SURICATA_QUEUE=${QUEUE_NUM}
FAIL_CLOSED=$([ "$FAIL_MODE" = "fail-closed" ] && echo 1 || echo 0)
EOF

# ---------------------------------------------------------------
# 3. Configure Suricata for inline (NFQUEUE) + EVE JSON
# ---------------------------------------------------------------
echo "[+] Configuring Suricata (af-packet copy-intact + NFQUEUE on ${IFACE})..."
cp -n "${CONFIG_DIR}/suricata.yaml" "${CONFIG_DIR}/suricata.yaml.orig" 2>/dev/null || true

IFACE="${IFACE}" FAIL_OPEN_YAML="${FAIL_OPEN_YAML}" python3 - <<'PY'
import re
p = "/etc/suricata/suricata.yaml"
s = open(p).read()

# Enable NFQUEUE inline mode (fail-open per env; interface pinned to chosen IFACE)
nfq = '''nfqueue:
  - queue-num: %s
    fail-open: %s
    repeat-mark: no
    repeat-mask: 0x00
    bypass-mark: no
''' % (open("/etc/suricata-ips.conf").read().split("SURICATA_QUEUE=")[1].splitlines()[0],
       __import__("os").environ["FAIL_OPEN_YAML"])

if "nfqueue:" not in s:
    # insert before 'af-packet:' (line-start anchored, comment-safe)
    s = re.sub(r"(?m)^af-packet:", nfq + "\naf-packet:", s, count=1)
else:
    s = re.sub(r"(?m)^nfqueue:.*?(?=\n\S|\Z)", nfq, s, flags=re.S)

# Pin af-packet capture interface to the SAME interface NFQUEUE hooks.
# Suricata needs a capture source even in NFQUEUE mode for copies/alerts.
iface = __import__("os").environ["IFACE"]
s = re.sub(r"(?m)^(-\s*interface:\s*)\S+", r"\g<1>" + iface, s, count=1)

# CRITICAL FIX (testbox2 incident 2026-09-09):
# Suricata in IPS mode DROPS packets of flows it considers "midstream"
# (stream started before Suricata did — e.g. the Wazuh agent<->manager TCP
# session, an SSH session, anything alive at install time). Drop stats showed
# stream_midstream + flow_drop killing the agent connection to :1514.
# midstream: true + midstream-policy: pass-flow lets those pre-existing
# flows continue (uninspected) instead of killing them.
# (7.0.x valid policies: drop-flow, pass-flow, bypass, reject,
#  drop-packet, pass-packet, ignore, auto — NOT accept-flow)
stream_fix = '''stream:
  memcap: 64mb
  checksum-validation: no
  inline: auto
  midstream: true
  midstream-policy: pass-flow
  async-oneside: true
  reassembly:
    memcap: 256mb
    depth: 1mb
    toserver-chunk-size: 2560
    toclient-chunk-size: 2560
    randomize-chunk-size: no
'''
if re.search(r"(?m)^stream:", s):
    s = re.sub(r"(?m)^stream:.*?(?=\n[a-zA-Z0-9_#-]+:|\Z)", stream_fix, s, flags=re.S)
else:
    s = s + "\n" + stream_fix

# Ensure EVE JSON outputs to file (Wazuh reads it) + JA3 fingerprinting enabled
eve_block = '''  - eve-log:
      enabled: yes
      filetype: regular
      filename: eve.json
      pcap-file: false
      types:
        - alert:
            metadata: yes
            tagged-packets: yes
        - anomaly:
        - http:
        - dns:
        - tls:
            extended: yes
            ja3-fingerprints: yes
        - flow
        - ssh
        - stats:
            totals: yes
'''
s = re.sub(r"  - eve-log:.*?(?=\n  - |\noutputs:|\Z)", eve_block, s, flags=re.S)

open(p, "w").write(s)
print("[+] suricata.yaml patched (nfqueue fail-open=%s, af-packet iface=%s)" % ("yes" if "fail-open: yes" in nfq else "no", iface))
PY

# ---------------------------------------------------------------
# 3b. Download ruleset (ET Open) — zero rules = blind IPS
# ---------------------------------------------------------------
echo "[+] Fetching rules via suricata-update (ET Open)..."
if ! suricata-update update-sources >/dev/null 2>&1; then
    echo "[WARN] suricata-update update-sources failed (offline?) — continuing with existing rules"
fi
suricata-update enable-source et/open >/dev/null 2>&1 || true
if ! suricata-update; then
    echo "[WARN] suricata-update rule download failed — continuing with existing rules"
fi

# Apply alert -> drop conversions BEFORE validation (drop.list present only)
if [ -f "${SCRIPT_DIR}/suricata-drop-apply.sh" ] && [ -f /etc/suricata-drop.list ]; then
    echo "[+] Applying alert->drop rule conversions from /etc/suricata-drop.list..."
    bash "${SCRIPT_DIR}/suricata-drop-apply.sh" || true
fi

# ---------------------------------------------------------------
# 3c. VALIDATE config BEFORE any inline hook is built.
#     The old script wired NFQUEUE first and THEN discovered Suricata
#     couldn't start => every packet hit the tail DROP => network cut.
# ---------------------------------------------------------------
echo "[+] Validating suricata.yaml + rules (suricata -T)..."
if ! suricata -T -c "${CONFIG_DIR}/suricata.yaml" >/tmp/suricata-T.log 2>&1; then
    tail -20 /tmp/suricata-T.log >&2
    fail "Config validation FAILED. Not installing NFQUEUE hook — host traffic untouched. Fix config and re-run."
fi
echo "[OK] Config validated."

# ---------------------------------------------------------------
# 4. Build iptables NFQUEUE chain
#    CRITICAL: Management bypass (SSH, Wazuh Agent ports 22, 1514, 1515)
#    and established connections must NEVER be held by NFQUEUE.
#    Also, NFQUEUE MUST have --queue-bypass so if Suricata restarts
#    or is busy loading rules, the kernel forwards packets instead of dropping!
# ---------------------------------------------------------------
echo "[+] Installing iptables SURICATA_IPS chain..."

# Idempotent: flush+rebuild the chain
iptables -w -F SURICATA_IPS 2>/dev/null || iptables -w -N SURICATA_IPS

# 1. Trusted-source bypass (Tier-2 hardening 2026-09-09):
#    management/scanner boxes never enter NFQUEUE -> zero self-block risk,
#    fewer false positives, engine load reduced. Extend via
#    SURICATA_TRUSTED_IPS="ip1 ip2 ...".
for TIP in $TRUSTED_IPS; do
    echo "$TIP" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' || { echo "[WARN] invalid trusted IP '$TIP' skipped"; continue; }
    iptables -w -A SURICATA_IPS -s "$TIP" -j ACCEPT
    iptables -w -A SURICATA_IPS -d "$TIP" -j ACCEPT
done

# 2. Management safety bypass: SSH (22) + Wazuh (1514, 1515)
iptables -w -A SURICATA_IPS -p tcp -m multiport --dports 22,1514,1515 -j ACCEPT
iptables -w -A SURICATA_IPS -p tcp -m multiport --sports 22,1514,1515 -j ACCEPT

# 2. Optional: bypass ALL established flows (maximum safety, minimum detection).
#    Off by default — midstream:true + accept-flow already handles existing
#    sessions. Enable with SURICATA_SKIP_ESTABLISHED=1 if you want it anyway.
if [ "${SURICATA_SKIP_ESTABLISHED:-0}" = "1" ]; then
    iptables -w -A SURICATA_IPS -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT 2>/dev/null || true
fi

# 3. Send remaining traffic into NFQUEUE with --queue-bypass
iptables -w -A SURICATA_IPS -j NFQUEUE --queue-num "${QUEUE_NUM}" --queue-bypass

# 4. Tail fallback
iptables -w -A SURICATA_IPS -j "${IPT_TAIL}"

# ---------------------------------------------------------------
# 5. systemd unit (watchdog + restart)
# ---------------------------------------------------------------
echo "[+] Installing systemd unit..."
# Rebuild trusted bypass as one shell fragment for ExecStartPre.
# ponytail: string concat in bash, no arrays — fine for <=20 IPs; switch to a
# generated drop-in unit (ExecStartPre= lines) if the list ever grows.
EXECSTARTPRE_TRUSTED=""
for TIP in $TRUSTED_IPS; do
    echo "$TIP" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' || continue
    EXECSTARTPRE_TRUSTED="${EXECSTARTPRE_TRUSTED}/sbin/iptables -w -A SURICATA_IPS -s ${TIP} -j ACCEPT; /sbin/iptables -w -A SURICATA_IPS -d ${TIP} -j ACCEPT; "
done
cat > /etc/systemd/system/${NAME}.service <<EOF
[Unit]
Description=Suricata Inline IPS (NFQUEUE)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStartPre=/bin/bash -c '/bin/rm -f /run/${NAME}.pid; /sbin/iptables -w -N SURICATA_IPS 2>/dev/null; /sbin/iptables -w -F SURICATA_IPS; ${EXECSTARTPRE_TRUSTED}/sbin/iptables -w -A SURICATA_IPS -p tcp -m multiport --dports 22,1514,1515 -j ACCEPT; /sbin/iptables -w -A SURICATA_IPS -p tcp -m multiport --sports 22,1514,1515 -j ACCEPT; /sbin/iptables -w -A SURICATA_IPS -j NFQUEUE --queue-num ${QUEUE_NUM} --queue-bypass; /sbin/iptables -w -A SURICATA_IPS -j ${IPT_TAIL}'
ExecStart=/usr/bin/suricata -c ${CONFIG_DIR}/suricata.yaml -q ${QUEUE_NUM}
ExecStopPost=/sbin/iptables -w -F SURICATA_IPS
Restart=always
RestartSec=3
IgnoreSIGUSR1=yes
# No WatchdogSec: Suricata 8 inline startup exceeds the default 30s notify
# window and systemd would SIGABRT it. Suricata manages its own liveness.
TimeoutStartSec=120
LimitNOFILE=65535

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable ${NAME} --now
systemctl restart ${NAME}

# Hook into INPUT, FORWARD, and OUTPUT only AFTER service is running.
# OUTPUT matters for host-generated traffic: JA3 fingerprints are computed
# from the CLIENT hello, which only the engine sees if outbound is hooked.
echo "[+] Hooking SURICATA_IPS into iptables INPUT, FORWARD, OUTPUT..."
iptables -w -D FORWARD -i "${IFACE}" -j SURICATA_IPS 2>/dev/null || true
iptables -w -D INPUT   -i "${IFACE}" -j SURICATA_IPS 2>/dev/null || true
iptables -w -D OUTPUT  -o "${IFACE}" -j SURICATA_IPS 2>/dev/null || true
iptables -w -I FORWARD -i "${IFACE}" -j SURICATA_IPS
iptables -w -I INPUT   -i "${IFACE}" -j SURICATA_IPS
iptables -w -I OUTPUT  -o "${IFACE}" -j SURICATA_IPS

# Persist (best effort)
if command -v netfilter-persistent >/dev/null 2>&1; then
    netfilter-persistent save 2>/dev/null || true
fi

# ---------------------------------------------------------------
# 5b. Post-start verification: engine must be ALIVE with the hook
#     installed, else rip the hook back out (fail-open safety net).
# ---------------------------------------------------------------
sleep 5
if ! systemctl is-active --quiet ${NAME}; then
    echo "[WARN] ${NAME} not active after start — removing NFQUEUE hook so traffic flows."
    iptables -w -D FORWARD -i "${IFACE}" -j SURICATA_IPS 2>/dev/null || true
    iptables -w -D INPUT   -i "${IFACE}" -j SURICATA_IPS 2>/dev/null || true
    iptables -w -F SURICATA_IPS 2>/dev/null || true
    systemctl status ${NAME} --no-pager -l | tail -15 >&2 || true
    fail "Suricata failed to start; hook removed. See journalctl -u ${NAME}."
fi

# ---------------------------------------------------------------
# 6. Wazuh locfile forward of eve.json
# ---------------------------------------------------------------
if [ -d "${WAZUH_OSSEC}/etc" ]; then
    echo "[+] Registering Wazuh localfile for ${EVE_LOG} (XML-safe via ElementTree)"
    LOCAL="${WAZUH_OSSEC}/etc/ossec.conf"
    if ! grep -q "suricata/eve.json" "${LOCAL}"; then
        cp -p "${LOCAL}" "${LOCAL}.bak.suricata-ips"
        BAK_MODE=$(stat -c '%a' "${LOCAL}"); BAK_OWNER=$(stat -c '%u:%g' "${LOCAL}")
        python3 - <<PY
import xml.etree.ElementTree as ET
p = "${WAZUH_OSSEC}/etc/ossec.conf"
tree = ET.parse(p)                       # fail loudly if conf already corrupt
root = tree.getroot()
lf = ET.SubElement(root, 'localfile')
ET.SubElement(lf, 'log_format').text = 'json'
ET.SubElement(lf, 'location').text = '/var/log/suricata/eve.json'
tree.write(p)
print("[+] localfile injected, XML valid")
PY
        # tree.write() recreates the file root:root 0644 -> restore agent ownership
        chown "${BAK_OWNER}" "${LOCAL}"; chmod "${BAK_MODE}" "${LOCAL}"
        python3 -c "import xml.etree.ElementTree as ET; ET.parse('${WAZUH_OSSEC}/etc/ossec.conf')" || fail "ossec.conf became invalid XML — restoring backup"
        systemctl restart wazuh-agent 2>/dev/null || true
        sleep 3
        systemctl is-active wazuh-agent >/dev/null 2>&1 || fail "wazuh-agent not active after ossec.conf edit"
    fi
fi

# ---------------------------------------------------------------
# 7. Health + rule refresh timers (same as IDS installer)
# ---------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BASE_DIR="$(dirname "$SCRIPT_DIR")"
if [ -f "${SCRIPT_DIR}/suricata-health-monitor.sh" ]; then
    cp "${SCRIPT_DIR}/suricata-health-monitor.sh" /usr/local/bin/
    cp "${SCRIPT_DIR}/refresh-suricata-rules.sh" /usr/local/bin/
    [ -f "${SCRIPT_DIR}/suricata-drop-apply.sh" ] && cp "${SCRIPT_DIR}/suricata-drop-apply.sh" /usr/local/bin/
    chmod 755 /usr/local/bin/suricata-health-monitor.sh /usr/local/bin/refresh-suricata-rules.sh /usr/local/bin/suricata-drop-apply.sh 2>/dev/null
    cp "${BASE_DIR}/etc/suricata-health.service" /etc/systemd/system/ 2>/dev/null || true
    cp "${BASE_DIR}/etc/suricata-health.timer" /etc/systemd/system/ 2>/dev/null || true
    cp "${BASE_DIR}/etc/suricata-rules.service" /etc/systemd/system/ 2>/dev/null || true
    cp "${BASE_DIR}/etc/suricata-rules.timer" /etc/systemd/system/ 2>/dev/null || true
    cp "${BASE_DIR}/etc/suricata-logrotate" /etc/logrotate.d/suricata 2>/dev/null || true
    systemctl daemon-reload
    systemctl enable --now suricata-health.timer suricata-rules.timer 2>/dev/null || true
fi

# ---------------------------------------------------------------
# 8. Auto-block dispatcher (IPS only) — daemon + AR helper + unit
#    ET Open free ships 0 `drop` rules, so signature hits do NOT
#    packet-drop in NFQUEUE; this dispatcher is the real block path
#    (iptables WAZUH_SURICATA_BLOCK, 1h TTL). RFC1918 is whitelisted
#    by default — internal test sources are intentionally never blocked.
# ---------------------------------------------------------------
if [ -f "${SCRIPT_DIR}/suricata-ar-dispatch.sh" ]; then
    echo "[+] Installing auto-block dispatcher (bruteforce/C2/recon)..."
    cp "${SCRIPT_DIR}/suricata-ar-dispatch.sh" /usr/local/bin/
    cp "${BASE_DIR}/active-response/suricata-ip-block.sh" /usr/local/bin/
    chmod 755 /usr/local/bin/suricata-ar-dispatch.sh /usr/local/bin/suricata-ip-block.sh
    cp "${BASE_DIR}/etc/suricata-ar-dispatch.service" /etc/systemd/system/ 2>/dev/null || true
    if [ ! -f /etc/systemd/system/suricata-ar-dispatch.service.d/override.conf ]; then
        mkdir -p /etc/systemd/system/suricata-ar-dispatch.service.d
        cp "${BASE_DIR}/etc/suricata-ar-dispatch.override.conf.example" \
           /etc/systemd/system/suricata-ar-dispatch.service.d/override.conf 2>/dev/null || true
    fi
    systemctl daemon-reload
    systemctl enable --now suricata-ar-dispatch.service 2>/dev/null || true
    sleep 2
    if systemctl is-active --quiet suricata-ar-dispatch; then
        echo "    dispatcher: active (RFC1918 whitelisted; edit WHITELIST in override.conf)"
    else
        echo "    [WARN] dispatcher not active — check: journalctl -u suricata-ar-dispatch"
    fi
fi

sleep 2
systemctl is-active ${NAME} || true
iptables -w -S SURICATA_IPS
echo ""
echo "[*] Rules loaded: $(suricata --build-info 2>/dev/null | grep -c '' >/dev/null && echo ok || echo '?') — check: grep -c 'alert' /var/lib/suricata/rules/suricata.rules 2>/dev/null || echo 0"
echo "[*] Trusted bypass IPs (skip NFQUEUE): ${TRUSTED_IPS:-none}"
echo "[*] JA3 TLS fingerprints: enabled in eve.json (tls.ja3 / ja3_hash)"
echo "Dashboard: look for 'suricata' decoder events in Wazuh."
echo "Uninstall: scripts/uninstall-suricata-all.sh"
