#!/bin/bash
#
# install-suricata-ips.sh
# ---------------------------------------------------------------------------
# Inline Suricata IPS installer for Linux (Wazuh sensor).
#
# What it does:
#   1. Installs Suricata with NFQUEUE (inline) support.
#   2. Builds an iptables FORWARD/INPUT chain that pushes traffic into
#      NFQUEUE where Suricata verdicts (accept/drop).
#   3. Hardens to FAIL-CLOSED: if Suricata dies, the queue stops draining
#      and the NFQUEUE rule falls through to a DROP target (no silent bypass).
#   4. Installs a systemd unit (with watchdog), EVE JSON output, and the
#      Wazuh localfile that forwards eve.json to the manager.
#
# Idempotent: re-running is safe. `uninstall-suricata-ips.sh` reverts it.
# ---------------------------------------------------------------------------

set -euo pipefail

NAME="suricata-ips"
QUEUE_NUM="${SURICATA_QUEUE:-0}"
IFACE="${SURICATA_IFACE:-$(ip -o route get 1.1.1.1 2>/dev/null | awk '{print $5; exit}')}"
WAZUH_OSSEC="/var/ossec"
EVE_LOG="/var/log/suricata/eve.json"
CONFIG_DIR="/etc/suricata"
ROLES_CONF="/etc/${NAME}.conf"

fail() { echo "[ERROR] $*" >&2; exit 1; }

[ "$EUID" -eq 0 ] || fail "Run as root (sudo)."

echo "=============================================="
echo "   Suricata Inline IPS Installer"
echo "=============================================="
echo "[*] Interface : ${IFACE:-(auto: $IFACE)}"
echo "[*] NFQUEUE   : ${QUEUE_NUM}"
echo ""

# ---------------------------------------------------------------
# 1. Install packages
# ---------------------------------------------------------------
echo "[+] Installing dependencies..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y --no-install-recommends \
    suricata \
    iptables \
    iproute2 \
    jq \
    ca-certificates
# Note: suricata 8.x ships suricata-update inside the main package,
# so it is NOT listed here (would cause a dpkg file-conflict on .deb overlap).

# Make sure the kernel module for NFQUEUE verdicts is present
modprobe nfnetlink_queue 2>/dev/null || true

# Stop any conflicting suricata.service (Ubuntu ships one from the OISF pkg)
# so NFQUEUE queue 0 is free for our unit.
if systemctl list-unit-files suricata.service >/dev/null 2>&1; then
    systemctl stop suricata.service 2>/dev/null || true
fi

# ---------------------------------------------------------------
# 2. Write tunables / role config
# ---------------------------------------------------------------
echo "[+] Writing ${ROLES_CONF}"
cat > "${ROLES_CONF}" <<EOF
# Generated by install-suricata-ips.sh -- edit to persist across reinstalls
SURICATA_IFACE=${IFACE}
SURICATA_QUEUE=${QUEUE_NUM}
FAIL_CLOSED=1
EOF

# ---------------------------------------------------------------
# 3. Configure Suricata for inline (NFQUEUE) + EVE JSON
# ---------------------------------------------------------------
echo "[+] Configuring Suricata (af-packet copy-intact + NFQUEUE)..."
cp -n "${CONFIG_DIR}/suricata.yaml" "${CONFIG_DIR}/suricata.yaml.orig" 2>/dev/null || true

# af-packet: keep it as a passive copy so we can still capture while inline
# NFQUEUE is the inline verdict path.
python3 - <<'PY'
import re, sys
p = "/etc/suricata/suricata.yaml"
s = open(p).read()

# Enable NFQUEUE inline mode
nfq = '''nfqueue:
  - queue-num: %s
    fail-open: no
    repeat-mark: no
    repeat-mask: 0x00
    bypass-mark: no
''' % (open("/etc/suricata-ips.conf").read().split("SURICATA_QUEUE=")[1].splitlines()[0])

if "nfqueue:" not in s:
    # insert before 'af-packet:'
    s = s.replace("af-packet:", nfq + "\naf-packet:", 1)
else:
    s = re.sub(r"nfqueue:.*?(\n\S|\Z)", nfq, s, flags=re.S)

# Ensure EVE JSON outputs to file (Wazuh reads it)
eve_block = '''  - eve-log:
      enabled: yes
      filetype: regular
      filename: eve.json
      pcap-file: false
      types:
        - alert:
            metadata: yes
            tagged-packets: yes
        - anomaly:
        - http:
        - dns:
        - tls:
            extended: yes
        - flow
        - ssh
        - stats:
            totals: yes
'''
s = re.sub(r"  - eve-log:.*?(?=\n  - |\noutputs:|\Z)", eve_block, s, flags=re.S)

open(p, "w").write(s)
print("[+] suricata.yaml patched")
PY

# ---------------------------------------------------------------
# 4. Build iptables NFQUEUE chain (fail-closed)
# ---------------------------------------------------------------
echo "[+] Installing iptables NFQUEUE chain..."

# Idempotent: flush+rebuild the chain
iptables -w -F SURICATA_IPS 2>/dev/null || iptables -w -N SURICATA_IPS
# Send matched traffic into NFQUEUE 0 for Suricata verdict (accept/drop).
iptables -w -A SURICATA_IPS -j NFQUEUE --queue-num "${QUEUE_NUM}"
# Fail-closed: if the verdict target is unavailable (engine/module gone),
# packets reach here and are dropped rather than bypassed.
iptables -w -A SURICATA_IPS -j DROP
# Hook into FORWARD and INPUT — idempotent (delete-then-insert)
iptables -w -D FORWARD -i "${IFACE}" -j SURICATA_IPS 2>/dev/null || true
iptables -w -D INPUT   -i "${IFACE}" -j SURICATA_IPS 2>/dev/null || true
iptables -w -I FORWARD -i "${IFACE}" -j SURICATA_IPS
iptables -w -I INPUT   -i "${IFACE}" -j SURICATA_IPS

# Persist (best effort)
if command -v netfilter-persistent >/dev/null 2>&1; then
    netfilter-persistent save 2>/dev/null || true
fi

# ---------------------------------------------------------------
# 5. systemd unit (with watchdog + restart)
# ---------------------------------------------------------------
echo "[+] Installing systemd unit..."
cat > /etc/systemd/system/${NAME}.service <<EOF
[Unit]
Description=Suricata Inline IPS (NFQUEUE)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStartPre=/bin/bash -c '/bin/rm -f /run/${NAME}.pid; /sbin/iptables -w -N SURICATA_IPS 2>/dev/null; /sbin/iptables -w -F SURICATA_IPS; /sbin/iptables -w -A SURICATA_IPS -j NFQUEUE --queue-num ${QUEUE_NUM}; /sbin/iptables -w -A SURICATA_IPS -j DROP'
ExecStart=/usr/bin/suricata -c ${CONFIG_DIR}/suricata.yaml -q ${QUEUE_NUM}
ExecStopPost=/sbin/iptables -w -F SURICATA_IPS
Restart=always
RestartSec=3
# No WatchdogSec: Suricata 8 inline startup exceeds the default 30s notify
# window and systemd would SIGABRT it. Suricata manages its own liveness.
TimeoutStartSec=120
LimitNOFILE=65535

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable ${NAME} --now
systemctl restart ${NAME}

# ---------------------------------------------------------------
# 6. Wazuh locfile forward of eve.json
# ---------------------------------------------------------------
if [ -d "${WAZUH_OSSEC}/etc" ]; then
    echo "[+] Registering Wazuh locfile for ${EVE_LOG}"
    LOCAL="${WAZUH_OSSEC}/etc/ossec.conf"
    if ! grep -q "suricata/eve.json" "${LOCAL}"; then
        cp "${LOCAL}" "${LOCAL}.bak.suricata-ips"
        python3 - <<PY
p = "${WAZUH_OSSEC}/etc/ossec.conf"
s = open(p).read()
block = '''  <ossec_config>
    <localfile>
      <log_format>json</log_format>
      <location>/var/log/suricata/eve.json</location>
    </localfile>'''
s = s.replace("<ossec_config>", block, 1)
open(p,"w").write(s)
PY
        systemctl restart wazuh-agent 2>/dev/null || true
    fi
fi

sleep 2
echo ""
echo "[OK] Suricata IPS active:"
systemctl is-active ${NAME} || true
iptables -w -S SURICATA_IPS
echo ""
echo "Dashboard: look for 'suricata' decoder events in Wazuh."
echo "Uninstall: scripts/uninstall-suricata-ips.sh"
