# refresh-suricata-ips-rules.ps1 - generated by build-suricata-ips.ps1
# Daily task: stage ET Open + agb rules, syntax-check every file, swap in
# with backup, validate full config via suricata -T, roll back on failure,
# restart the SuricataIPS service ONCE (only if it was already running).
$ErrorActionPreference = 'Continue'
$DeployRoot = 'C:\SuricataIPS'
$RuleDir    = 'C:\SuricataIPS\rules'
$WorkRoot   = 'C:\msys64\suricata-ips-build'
$RawBase    = 'https://raw.githubusercontent.com/yekyawhan/wazuh/git-home/suricata-win'
# GOTCHA FIXED (2026-07-17): this line did not exist, yet the generator below
# calls .Replace('C:\Program Files (x86)\ossec-agent\shared\suricata-win-offline', ...) and Copy-LocalRulesFile reads
# $LocalRulesRepo. Replacing a token that appears nowhere is a silent no-op,
# so $LocalRulesRepo was always $null here, every `if ($LocalRulesRepo -and ...)`
# was false, and the agb-* rules were ALWAYS pulled from GitHub - never from
# the Wazuh shared folder, even on an agent where the manager is the source of
# truth. That is the "two sources of truth" split: rules edited on the manager
# were invisible to this refresh, which then overwrote them with GitHub's copy.
$LocalRulesRepo = 'C:\Program Files (x86)\ossec-agent\shared\suricata-win-offline'
$BlockTor   = $true
$LogFile    = "$WorkRoot\ips-scripts\refresh.log"
function RLog([string]$m) { "$(Get-Date -Format s) $m" | Add-Content -Path $LogFile }
if ((Test-Path $LogFile) -and ((Get-Item $LogFile).Length -gt 1MB)) { Remove-Item $LogFile -Force }

# A rules file may contain ONLY blank lines, comments, and
# pass/alert/drop/reject signatures. Anything else (truncated download,
# HTML error page, injected content) rejects the WHOLE file - the previous
# known-good copy stays in place.
function Test-RulesSane([string]$path, [int]$minRules) {
    if (-not (Test-Path $path)) { return $false }
    $count = 0
    foreach ($l in [IO.File]::ReadLines($path)) {
        $t = $l.Trim()
        if ($t -eq '' -or $t.StartsWith('#')) { continue }
        if ($t -match '^(pass|alert|drop|reject)\s') { $count++; continue }
        RLog "REJECT $path - unexpected content: $($t.Substring(0, [Math]::Min(120, $t.Length)))"
        return $false
    }
    if ($count -lt $minRules) { RLog "REJECT $path - only $count rules (expected >= $minRules)"; return $false }
    return $true
}

$Staging = "$WorkRoot\rules-staging"
if (Test-Path $Staging) { Remove-Item $Staging -Recurse -Force }
New-Item -ItemType Directory -Force -Path $Staging | Out-Null
$updated = @()

# ---- ET Open (with Content-Length verification) ----
try {
    $ver = (& "$DeployRoot\suricata.exe" -V 2>&1 | Select-String -Pattern '(\d+\.\d+\.\d+)' | Select-Object -First 1).Matches.Groups[1].Value
    $mm  = $ver.Substring(0, $ver.LastIndexOf('.'))
    $tarPath = "$Staging\emerging.rules.tar.gz"
    $got = $false
    foreach ($u in @("https://rules.emergingthreats.net/open/suricata-$ver/emerging.rules.tar.gz",
                     "https://rules.emergingthreats.net/open/suricata-$mm.0/emerging.rules.tar.gz",
                     "https://rules.emergingthreats.net/open/suricata-$mm/emerging.rules.tar.gz")) {
        try {
            $expected = (Invoke-WebRequest -Uri $u -Method Head -UseBasicParsing).Headers.'Content-Length' | Select-Object -Last 1
            Invoke-WebRequest -Uri $u -OutFile $tarPath -UseBasicParsing
            if ($expected -and ("$((Get-Item $tarPath).Length)" -ne "$expected")) { RLog "SIZE MISMATCH from $u - retrying next mirror"; continue }
            $got = $true; break
        } catch { RLog "ET download failed from $u : $($_.Exception.Message)" }
    }
    if ($got) {
        $extractDir = "$Staging\rules-extract"
        New-Item -ItemType Directory -Force -Path $extractDir | Out-Null
        & tar.exe -xzf $tarPath -C $extractDir
        $rfiles = Get-ChildItem (Join-Path $extractDir 'rules') -Filter *.rules -ErrorAction SilentlyContinue
        if (-not $rfiles) { $rfiles = Get-ChildItem $extractDir -Recurse -Filter *.rules }
        $sb = New-Object Text.StringBuilder
        foreach ($f in $rfiles) { [void]$sb.AppendLine([IO.File]::ReadAllText($f.FullName)) }
        [IO.File]::WriteAllText("$Staging\suricata.rules", $sb.ToString(), (New-Object Text.UTF8Encoding($false)))

        if ($BlockTor) {
            $etLines  = [IO.File]::ReadAllText("$Staging\suricata.rules") -split "`r?`n"
            $torLines = $etLines | Where-Object { $_ -match 'msg:"ET TOR (Known Tor Exit Node|Known Tor Relay/Router)' }
            if ($torLines.Count -gt 0) {
                $torDropText = ($torLines -join "`r`n") -replace '(?m)^alert tcp (\[[^\]]+\]) any -> \$HOME_NET any', 'drop tcp $HOME_NET any -> $1 any'
                $torDropText = $torDropText -replace 'threshold:\s*type limit,\s*track by_src,\s*seconds \d+,\s*count \d+;\s*', ''
                $stillAlert = ([regex]::Matches($torDropText, '(?m)^alert\s')).Count
                if ($stillAlert -gt 0) { RLog "WARN $stillAlert ET TOR line(s) did not match the direction-reversal pattern and remain alert-only (ET format drift?)" }
                [IO.File]::WriteAllText("$Staging\agb-tor-drop.rules", $torDropText, (New-Object Text.UTF8Encoding($false)))
                $kept = $etLines | Where-Object { $_ -notmatch 'msg:"ET TOR (Known Tor Exit Node|Known Tor Relay/Router)' }
                [IO.File]::WriteAllText("$Staging\suricata.rules", ($kept -join "`r`n"), (New-Object Text.UTF8Encoding($false)))
                if (Test-RulesSane "$Staging\agb-tor-drop.rules" 100) { $updated += 'agb-tor-drop.rules' }
            }
        }
        if (Test-RulesSane "$Staging\suricata.rules" 10000) { $updated += 'suricata.rules' }
    }
} catch { RLog "ET refresh error: $($_.Exception.Message)" }

# ---- agb rules from local repo (or GitHub fallback) ----
function Copy-LocalRulesFile([string]$localRelPath, [string]$stagingName) {
    $src = Join-Path $LocalRulesRepo $localRelPath
    if (Test-Path $src) { Copy-Item $src "$Staging\$stagingName" -Force; return $true }
    return $false
}
try {
    if ($LocalRulesRepo -and (Copy-LocalRulesFile 'rules\agb-black.rules' 'agb-black-src.rules')) {
        RLog "agb-black.rules read from local: $(Join-Path $LocalRulesRepo 'rules\agb-black.rules')"
    } else {
        Invoke-WebRequest -Uri "$RawBase/agb-black.rules" -OutFile "$Staging\agb-black-src.rules" -UseBasicParsing
    }
    $dropText = [regex]::Replace([IO.File]::ReadAllText("$Staging\agb-black-src.rules"), '(?m)^alert\s', 'drop ')
    [IO.File]::WriteAllText("$Staging\agb-black-drop.rules", $dropText, (New-Object Text.UTF8Encoding($false)))
    if (Test-RulesSane "$Staging\agb-black-drop.rules" 1) { $updated += 'agb-black-drop.rules' }
} catch { RLog "agb-black download failed: $($_.Exception.Message)" }
foreach ($rf in @('agb-white.rules', 'agb-heuristics.rules')) {
    try {
        if ($LocalRulesRepo -and (Copy-LocalRulesFile "rules\$rf" $rf)) {
            RLog "$rf read from local: $(Join-Path $LocalRulesRepo "rules\$rf")"
        } else {
            Invoke-WebRequest -Uri "$RawBase/$rf" -OutFile "$Staging\$rf" -UseBasicParsing
        }
        if (Test-RulesSane "$Staging\$rf" 1) { $updated += $rf }
    } catch { RLog "$rf download failed: $($_.Exception.Message)" }
}

if ($updated.Count -eq 0) { RLog "nothing passed validation - current rules left untouched"; exit 0 }

# ---- swap with backup + suricata -T validation + rollback ----
$BackupDir = "$WorkRoot\rules-backup"
if (Test-Path $BackupDir) { Remove-Item $BackupDir -Recurse -Force }
New-Item -ItemType Directory -Force -Path $BackupDir | Out-Null
# GOTCHA FIXED (2026-07-17, destroyed live rules): rollback used to be
#   if (Test-Path "$BackupDir\$f") { restore } else { Remove-Item "$RuleDir\$f" }
# i.e. "no backup? delete it". If the backup copy silently failed, that
# deleted a perfectly good live rule file. Confirmed live: agb-white.rules,
# agb-black-drop.rules and agb-tor-drop.rules were all destroyed, which made
# suricata -T fail on a MISSING file, which made the next run roll back and
# delete more - a self-perpetuating loop that ended with the engine one
# restart away from having no rules at all.
# Now: track exactly what we touched, verify each backup actually landed
# BEFORE overwriting anything, and only ever remove files this run created.
$replaced = @()   # existed before -> restore from backup on rollback
$added    = @()   # did not exist before -> safe to remove on rollback
foreach ($f in $updated) {
    if (Test-Path "$RuleDir\$f") {
        Copy-Item "$RuleDir\$f" "$BackupDir\$f" -Force
        if (-not (Test-Path "$BackupDir\$f")) {
            RLog "ABORT: could not back up $f - refusing to touch the live rules"
            exit 1
        }
        $replaced += $f
    } else {
        $added += $f
    }
    Copy-Item "$Staging\$f" "$RuleDir\$f" -Force
}

# GOTCHA FIXED (2026-07-17): this gate was `if ($LASTEXITCODE -ne 0)`, but
# suricata -T on Windows ALWAYS exits 1 - ET Open ships 9 signatures using the
# file.magic keyword and this build has no libmagic. So the gate tripped on
# EVERY run since the day it was generated: this script never once succeeded,
# it rolled back 100% of the time, and the rollback above then ate the rule
# files. Runtime proves the errors are harmless - the service logs
# "51518 rules successfully loaded, 9 rules failed" and inspects traffic fine.
# "Loading signatures failed" is filtered too: Suricata prints it whenever ANY
# rule fails to parse, even though it carries on and loads all the others. A
# REAL fault always emits its own specific E: line (e.g. "opening rule file
# ...: No such file or directory") - that is what this gate catches.
# Same rule Step 14 and deploy-agb-rules.ps1 already apply. NEVER gate on the
# exit code alone.
$testOut = & "$DeployRoot\suricata.exe" -c "$DeployRoot\suricata.yaml" -T 2>&1
$errLines   = @($testOut | Where-Object { "$_" -match '^E:' })
$realErrors = @($errLines | Where-Object { "$_" -notmatch 'file\.magic' -and "$_" -notmatch 'Loading signatures failed' })
if ($realErrors.Count -gt 0) {
    RLog "suricata -T found REAL errors (not the harmless file.magic ones) - rolling back: $($updated -join ', ')"
    foreach ($e in ($realErrors | Select-Object -First 5)) { RLog "    $e" }
    foreach ($f in $replaced) { Copy-Item "$BackupDir\$f" "$RuleDir\$f" -Force }
    foreach ($f in $added)    { Remove-Item "$RuleDir\$f" -Force -ErrorAction SilentlyContinue }
    RLog "rolled back to previous rules - service left running on the old ruleset"
    exit 1
}
if ($errLines.Count -gt 0) { RLog "validated OK (ignored $($errLines.Count) expected file.magic error line(s)) - applied: $($updated -join ', ')" }
else { RLog "validated OK - applied: $($updated -join ', ')" }

# ---- single service restart, only if it was already running ----
$svc = Get-Service -Name 'SuricataIPS' -ErrorAction SilentlyContinue
if ($svc -and $svc.Status -eq 'Running') {
    Restart-Service -Name 'SuricataIPS' -Force -ErrorAction SilentlyContinue
    RLog "SuricataIPS restarted with refreshed rules"
}