#!/bin/bash
# hybrid_sync_usb_linux.sh
# Reads usb_whitelist.txt from Wazuh shared folder and applies to udev rules.
#
# FIXES vs previous version:
#  - SUBSYSTEMS -> SUBSYSTEM (singular) for setting ATTR{authorized}.
#  - Default-deny scoped to USB MASS-STORAGE (interface class 08) instead of ALL
#    USB, so pushing this fleet-wide does NOT deauthorize USB keyboards/mice.
#    Set BLOCK_ALL=1 below to block everything (only if inputs are built-in or
#    whitelisted).
#  - Whitelist rules come FIRST and GOTO past the deny, so an allowed device is
#    never logged as blocked.
#  - Each block is logged via `logger -t usb-block` so Wazuh can alert on it.

WHITELIST_FILE="/var/ossec/etc/shared/usb_whitelist.txt"
UDEV_RULE_FILE="/etc/udev/rules.d/99-usb-block.rules"
LOG_FILE="/var/ossec/logs/active-responses.log"
BLOCK_ALL=0     # 0 = block USB storage only (safe default); 1 = block ALL usb

write_log() {
    local message="$1"
    local timestamp=$(date "+%Y-%m-%d %H:%M:%S")
    echo "$timestamp - hybrid_sync_usb_linux - $message" >> "$LOG_FILE"
    echo "$message"
}

if [ ! -f "$WHITELIST_FILE" ]; then
    write_log "Error: Whitelist file not found in Wazuh shared folder ($WHITELIST_FILE)."
    exit 1
fi

LOGGER="$(command -v logger || echo /usr/bin/logger)"

{
    echo "# Auto-generated by Wazuh Hybrid USB Sync - do not edit manually"
    echo ""
    echo "# 1) Whitelist FIRST: authorize approved devices and skip the deny below."
} > "$UDEV_RULE_FILE"

PROCESSED_IDS=""

# Parse the whitelist (Format: 0951:1666  OR  USB\VID_0951&PID_1666)
while IFS= read -r line; do
    [[ -z "$line" || "$line" == \#* ]] && continue

    if [[ "$line" =~ VID_([0-9A-Fa-f]{4})\&PID_([0-9A-Fa-f]{4}) ]]; then
        vid="${BASH_REMATCH[1]}"; pid="${BASH_REMATCH[2]}"
    elif [[ "$line" =~ ^([0-9A-Fa-f]{4}):([0-9A-Fa-f]{4})$ ]]; then
        vid="${BASH_REMATCH[1]}"; pid="${BASH_REMATCH[2]}"
    else
        continue
    fi

    vid=$(echo "$vid" | tr '[:upper:]' '[:lower:]')
    pid=$(echo "$pid" | tr '[:upper:]' '[:lower:]')

    echo "ACTION==\"add\", SUBSYSTEM==\"usb\", ATTR{idVendor}==\"$vid\", ATTR{idProduct}==\"$pid\", ATTR{authorized}=\"1\", GOTO=\"usb_block_end\"" >> "$UDEV_RULE_FILE"
    PROCESSED_IDS="$PROCESSED_IDS $vid:$pid"
done < "$WHITELIST_FILE"

{
    echo ""
    if [[ "$BLOCK_ALL" -eq 1 ]]; then
        echo "# 2) Deny ALL other USB devices + log for Wazuh."
        echo "ACTION==\"add\", SUBSYSTEM==\"usb\", ATTR{authorized}=\"0\", RUN+=\"$LOGGER -t usb-block DENIED unauthorized USB kernel=%k vendor=\$attr{idVendor} product=\$attr{idProduct}\""
    else
        echo "# 2) Deny USB MASS-STORAGE only (interface class 08) + log for Wazuh."
        echo "#    Non-storage devices (keyboard/mouse/etc.) are left untouched."
        echo "ACTION==\"add\", SUBSYSTEM==\"usb\", ENV{ID_USB_INTERFACES}==\"*:08????:*\", ATTR{authorized}=\"0\", RUN+=\"$LOGGER -t usb-block DENIED unauthorized USB storage kernel=%k vendor=\$attr{idVendor} product=\$attr{idProduct}\""
    fi
    echo ""
    echo "LABEL=\"usb_block_end\""
} >> "$UDEV_RULE_FILE"

udevadm control --reload-rules
udevadm trigger --subsystem-match=usb --action=add

write_log "Success: Linux USB udev rules updated from Wazuh Centralized Config. Authorized IDs:${PROCESSED_IDS}"
