#!/bin/bash
# hybrid_sync_usb_linux.sh
# Reads usb_whitelist.txt from Wazuh shared folder and applies to udev rules

WHITELIST_FILE="/var/ossec/etc/shared/usb_whitelist.txt"
UDEV_RULE_FILE="/etc/udev/rules.d/99-usb-block.rules"

if [ ! -f "$WHITELIST_FILE" ]; then
    echo "Whitelist file not found in Wazuh shared folder ($WHITELIST_FILE). Exiting."
    exit 1
fi

echo "# Auto-generated by Wazuh Hybrid USB Sync" > "$UDEV_RULE_FILE"
echo "# Block all USB storage by default" >> "$UDEV_RULE_FILE"
echo 'ACTION=="add", SUBSYSTEMS=="usb", ATTR{authorized}="0"' >> "$UDEV_RULE_FILE"
echo "" >> "$UDEV_RULE_FILE"
echo "# Allowed USB Devices" >> "$UDEV_RULE_FILE"

# Parse the whitelist (Format expected: 0951:1666 or USB\VID_0951&PID_1666)
while IFS= read -r line; do
    # Skip empty lines and comments
    [[ -z "$line" || "$line" == \#* ]] && continue

    # Extract VID and PID. Handles both Windows format (USB\VID_1234&PID_5678) and Linux format (1234:5678)
    if [[ "$line" =~ VID_([0-9A-Fa-f]{4})\&PID_([0-9A-Fa-f]{4}) ]]; then
        vid="${BASH_REMATCH[1]}"
        pid="${BASH_REMATCH[2]}"
    elif [[ "$line" =~ ^([0-9A-Fa-f]{4}):([0-9A-Fa-f]{4})$ ]]; then
        vid="${BASH_REMATCH[1]}"
        pid="${BASH_REMATCH[2]}"
    else
        continue # Skip invalid lines
    fi

    # Convert to lowercase for udev
    vid=$(echo "$vid" | tr '[:upper:]' '[:lower:]')
    pid=$(echo "$pid" | tr '[:upper:]' '[:lower:]')

    echo "ACTION==\"add\", SUBSYSTEMS==\"usb\", ATTR{idVendor}==\"$vid\", ATTR{idProduct}==\"$pid\", ATTR{authorized}=\"1\"" >> "$UDEV_RULE_FILE"
done < "$WHITELIST_FILE"

echo "Reloading udev rules..."
udevadm control --reload-rules
udevadm trigger

echo "Linux USB udev rules updated successfully from Wazuh Centralized Config."
