#!/bin/bash
# ==============================================================================
# YARA rules updater - pulls the whole rule collection from OUR GitHub repo
# (yara/rule-collection/: our own rules + vendored community signatures).
# Installed to /usr/local/bin/update-yara-rules.sh by install.sh
# Builds /var/ossec/yara/rules/index.yar which yara.sh scans with.
#
# Community rules use external vars (filename/filepath/extension/filetype/
# owner) - the AR script defines them with -d, and so do the compile checks.
# ==============================================================================
set -u

REPO_TARBALL="https://github.com/yekyawhan/wazuh/archive/refs/heads/git-home.tar.gz"

# Valhalla (Nextron) rule feed. Replace VALHALLA_APIKEY with your real key;
# "demo" only returns a small sample set. Set VALHALLA_APIKEY="" to skip.
VALHALLA_APIKEY="${VALHALLA_APIKEY:-1111111111111111111111111111111111111111111111111111111111111111}"

RULES_DIR="/var/ossec/yara/rules"
INDEX="$RULES_DIR/index.yar"
LOG="/var/log/yara-update.log"
EXTVARS=(-d filename="" -d filepath="" -d extension="" -d filetype="" -d owner="")

log() { echo "[$(date)] $*" >> "$LOG"; echo "$*"; }
compiles() { yara -w "${EXTVARS[@]}" "$1" /dev/null > /dev/null 2>&1; }

mkdir -p "$RULES_DIR"
log "Starting YARA rules update from our repo..."

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

if ! curl -fsSL "$REPO_TARBALL" -o "$TMP/repo.tar.gz" || ! tar -xzf "$TMP/repo.tar.gz" -C "$TMP"; then
    log "ERROR: repo download failed; keeping previous rules."
    exit 1
fi

SRC=$(find "$TMP" -maxdepth 3 -type d -path "*/yara/rule-collection" | head -1)
if [ -z "$SRC" ]; then
    log "ERROR: rule-collection not found in repo tarball; keeping previous rules."
    exit 1
fi

# Pull Valhalla feed into the collection so it is staged/compiled like the rest.
# On failure we keep going with the repo rules only (never abort the update).
if [ -n "$VALHALLA_APIKEY" ]; then
    if curl -fsSL 'https://valhalla.nextron-systems.com/api/v1/get' \
        -H 'Accept: text/plain' \
        -H 'Content-Type: application/x-www-form-urlencoded' \
        -H 'Referer: https://valhalla.nextron-systems.com/' \
        --compressed \
        --data "demo=demo&apikey=${VALHALLA_APIKEY}&format=text" \
        -o "$SRC/valhalla.yar" \
       && yara -w "${EXTVARS[@]}" "$SRC/valhalla.yar" /dev/null >/dev/null 2>&1; then
        log "Valhalla feed downloaded and compiles OK."
    else
        rm -f "$SRC/valhalla.yar"
        log "WARN: Valhalla download failed or did not compile; skipping it this run."
    fi
fi

# Stage: keep only files that compile individually
STAGE="$TMP/stage"
mkdir -p "$STAGE"
kept=0; dropped=0
while IFS= read -r -d '' f; do
    rel=${f#"$SRC"/}
    if compiles "$f"; then
        mkdir -p "$STAGE/$(dirname "$rel")"
        cp "$f" "$STAGE/$rel"
        kept=$((kept+1))
    else
        dropped=$((dropped+1))
        log "WARN: dropped $rel (does not compile)."
    fi
done < <(find "$SRC" -name '*.yar' -type f -print0)

if [ "$kept" -eq 0 ]; then
    log "ERROR: no rule file compiled; keeping previous rules."
    exit 1
fi

# Build candidate index against the staged tree
build_index() {
    local base="$1" out="$2"
    echo "// Auto-generated by update-yara-rules.sh - do not edit" > "$out"
    find "$base" -name '*.yar' -type f | sort | while IFS= read -r f; do
        echo "include \"$f\""
    done >> "$out"
}

build_index "$STAGE" "$TMP/index.yar"
if ! compiles "$TMP/index.yar"; then
    log "Combined index failed; pruning conflicting files..."
    echo "// Auto-generated by update-yara-rules.sh - do not edit" > "$TMP/index.yar"
    find "$STAGE" -name '*.yar' -type f | sort | while IFS= read -r f; do
        echo "include \"$f\"" >> "$TMP/index.yar"
        if ! compiles "$TMP/index.yar"; then
            sed -i '$d' "$TMP/index.yar"
            log "WARN: pruned ${f#"$STAGE"/} (conflicts in combined index)."
        fi
    done
fi

# Swap in atomically: copy staged tree under RULES_DIR, rewrite index paths
rm -rf "$RULES_DIR/collection.new"
cp -r "$STAGE" "$RULES_DIR/collection.new"
sed "s|$STAGE|$RULES_DIR/collection|g" "$TMP/index.yar" > "$INDEX.new"
rm -rf "$RULES_DIR/collection.old"
[ -d "$RULES_DIR/collection" ] && mv "$RULES_DIR/collection" "$RULES_DIR/collection.old"
mv "$RULES_DIR/collection.new" "$RULES_DIR/collection"
mv "$INDEX.new" "$INDEX"
rm -rf "$RULES_DIR/collection.old"

if compiles "$INDEX"; then
    log "index.yar rebuilt OK ($(grep -c '^include' "$INDEX") rule files; $kept kept, $dropped dropped)."
else
    log "ERROR: final index failed compile - investigate $INDEX"
    exit 1
fi

# Precompile to a single binary so yara.sh does NOT recompile 744 files on every
# scan. yara.sh loads index.yarc with -C when present; text index.yar is fallback.
COMPILED="$RULES_DIR/index.yarc"
if command -v yarac >/dev/null 2>&1 && yarac "${EXTVARS[@]}" "$INDEX" "$COMPILED.new" 2>/dev/null; then
    mv "$COMPILED.new" "$COMPILED"
    log "index.yarc precompiled OK (scans use compiled ruleset)."
else
    rm -f "$COMPILED.new" "$COMPILED"
    log "WARN: yarac precompile unavailable/failed; scans will use text index.yar."
fi

if systemctl is-active --quiet wazuh-agent; then
    systemctl restart wazuh-agent
    log "wazuh-agent restarted."
fi
log "YARA rules update finished."
