#!/bin/bash

set -e

WHITELIST="/var/ossec/etc/shared/usb_whitelist.txt"
RULE="/etc/udev/rules.d/99-usb-block.rules"
LOG="/var/log/wazuh-usb-sync.log"


log()
{
echo "$(date '+%F %T') $1" | tee -a "$LOG"
}


if [ ! -f "$WHITELIST" ]; then
    log "[ERROR] whitelist not found"
    exit 1
fi


TMP=$(mktemp)


grep -Ei \
'^[[:space:]]*([0-9a-f]{4}:[0-9a-f]{4}|USB\\VID_[0-9A-F]{4}&PID_[0-9A-F]{4})' \
"$WHITELIST" |
sed 's/^[[:space:]]*//' |
while read line
do

if [[ "$line" =~ USB\\VID_([0-9A-Fa-f]{4})\&PID_([0-9A-Fa-f]{4}) ]]
then
echo "${BASH_REMATCH[1]}:${BASH_REMATCH[2]}" >> "$TMP"

elif [[ "$line" =~ ([0-9a-fA-F]{4}):([0-9a-fA-F]{4}) ]]
then
echo "${BASH_REMATCH[1]}:${BASH_REMATCH[2]}" >> "$TMP"

fi

done


sort -u "$TMP" -o "$TMP"


cat > "$RULE" <<EOF
# Auto-generated by Wazuh USB Sync v2

EOF


while read ID
do

VID=$(echo $ID | cut -d: -f1 | tr 'A-F' 'a-f')
PID=$(echo $ID | cut -d: -f2 | tr 'A-F' 'a-f')


cat >> "$RULE" <<EOF
ACTION=="add", SUBSYSTEM=="usb", ATTR{idVendor}=="$VID", ATTR{idProduct}=="$PID", ATTR{authorized}="1", GOTO="usb_block_end"

EOF


done < "$TMP"



cat >> "$RULE" <<EOF

ACTION=="add", SUBSYSTEM=="usb", ENV{ID_USB_INTERFACES}=="*:08????:*", ATTR{authorized}="0", RUN+="/usr/bin/logger -t usb-block DENIED unauthorized USB storage kernel=%k vendor=\$attr{idVendor} product=\$attr{idProduct}"

LABEL="usb_block_end"
EOF



udevadm control --reload-rules

udevadm trigger --subsystem-match=usb --action=add


COUNT=$(wc -l < "$TMP")


log "[SUCCESS] USB rules updated. Authorized devices: $COUNT"


rm -f "$TMP"
